name: covid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.21.0
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.6
  convex_bottom_bar: ^3.0.0
  flutter_svg: 1.1.4
  websafe_svg: 2.1.2+2
  flutter_native_splash: 2.2.8
  video_player: 2.4.7
  chewie: 1.3.4
  flick_video_player: 0.5.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  image_picker_android: 0.8.5+2

flutter: 
  uses-material-design: true

flutter_native_splash: 
  image: assets/bg.png
  color: '#071b5d'

